# Generated by Django 6.0.3 on 2026-04-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.SlugField(unique=True)),
                ('train_name', models.CharField(max_length=120)),
                ('train_no', models.CharField(max_length=20)),
                ('from_station', models.CharField(max_length=80)),
                ('to_station', models.CharField(max_length=80)),
                ('departure', models.CharField(max_length=20)),
                ('arrival', models.CharField(max_length=20)),
                ('off_day', models.CharField(default='None', max_length=30)),
            ],
            options={
                'ordering': ['train_name'],
            },
        ),
    ]
