# Generated by Django 6.0.3 on 2026-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('division', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
