# Generated by Django 6.0.3 on 2026-04-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('compiled', models.CharField(max_length=50)),
                ('booking_portal', models.URLField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('gauge_legend', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=150, unique=True)),
                ('distance_km', models.CharField(blank=True, default='', max_length=50)),
                ('journey_time', models.CharField(blank=True, default='', max_length=50)),
                ('key_trains', models.JSONField(blank=True, default=list)),
                ('notable_stations', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['route'],
            },
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='gauge',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='key_stoppages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='schedule_group',
            field=models.CharField(default='intercity', max_length=30),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='source_sl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='train_type',
            field=models.CharField(default='Intercity', max_length=50),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
