# Generated by Django 6.0.3 on 2026-04-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datasetmetadata_routesummary_trainschedule_gauge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=120)),
                ('stop_order', models.PositiveIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trainschedule')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('train', 'stop_order')},
            },
        ),
    ]
