# Generated by Django 6.0.3 on 2026-04-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trainstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('line', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=150)),
                ('total_length_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_stations', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('ticket_info', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('last_updated', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=150)),
                ('toward_motijheel', models.JSONField(blank=True, default=dict)),
                ('toward_uttara_north', models.JSONField(blank=True, default=dict)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='api.metrosystem')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
